# Generated by Django 3.1.14 on 2021-12-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент - Рецепт', 'verbose_name_plural': 'Ингредиенты - Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег - Рецепт', 'verbose_name_plural': 'Теги - Рецепты'},
        ),
    ]
