# Generated by Django 3.1.14 on 2021-12-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211231_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcartrecipe',
            options={'verbose_name': 'Рецепт в списке покупок', 'verbose_name_plural': 'Рецепты в списке покупок'},
        ),
    ]
