# Generated by Django 3.1.14 on 2021-12-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211225_1837'),
        ('users', '0007_auto_20211231_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_recipe', to='recipes.recipe'),
        ),
    ]
